# Generated by Django 3.1.4 on 2020-12-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate',
            new_name='candidate_remark',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
